# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title ASS(ign) survey participants :)
#' @description This function generates all possible 0-1 assignment vectors of 2*n survey participants 
#' in such a way that exactly n of them are assigned to group 0 (control)
#' and the other n ones are assigned to group 1 (treatment). To simplyfy this task I have used  
#' std::next_permutation() - this suggestion I have found on stackoverflow.
#'
#' @param n - integer, number of participants in control or treatment group (both have equal size)
#' @return integer matrix, with all possible 0-1 participants assignments.
#'
#' @rdname ass
#'
#' @export
factorial <- function(n) {
    .Call('hw6package_factorial', PACKAGE = 'hw6package', n)
}

#' @rdname ass
#'
#' @export
ass <- function(n) {
    .Call('hw6package_ass', PACKAGE = 'hw6package', n)
}

#' @title Simple function calculating mode.
#' @description This function, given the input integer vector, calculates mode - the most 
#' frequently occurring value. If the mode is ambiguous it returns last one.
#'
#' @param integer vector
#' @return mode - single integer number -  the mode
#'
#' @export
mode <- function(x) {
    .Call('hw6package_mode', PACKAGE = 'hw6package', x)
}

#' @title List of vectors ==> Matrix
#' @description This function changes input list of numeric vectors to a matrix. 
#' We assume that vectors have equal length.
#'
#' @param vec_list - list of input numeric vectors
#' @return numeric matrix, where number of rows equals the length of the list and number of columns
#' equal the length of vectors in the list.
#'
#' @export
simplify2array <- function(vec_list) {
    .Call('hw6package_simplify2array', PACKAGE = 'hw6package', vec_list)
}

